version: '3.8'

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.2
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - ${WEAVIATE_DATA_PATH}:/var/lib/weaviate
    env_file:
      - .env

  weaviate-ui:
    image: naaive/weaviate-ui:latest
    ports:
      - "7777:7777"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_USERNAME=user1
      - WEAVIATE_PASSWORD=password1